.TH GOOGL 1
.SH NAME
googl \- command line interface to the Google url shortener
.SH SYNOPSIS
.B googl
.IR URL
.SH DESCRIPTION
Given a URL
.B googl
returns a short URL pointing to the URL given as produced by the Google url
shortener. In case the URL is already shortened the expanded URL is returned.
.SH EXAMPLES
googl
http://en.wikipedia.org

googl http://goo.gl/Y9So
.SH BUGS
Neither authentification nor passing multiple URLs is supported right now.
