#! /var/run/current-system/sw/bin/zsh

# BINARIES

CURL_BIN="$(which curl)"
ECHO_BIN=echo
GREP_BIN="$(which grep)"
SED_BIN="$(which sed)"

# STATIC VARIABLES

API=https://www.googleapis.com/urlshortener

# ARGUMENT VARIABLES

ACTION=shorten
HELP=0
URL="$1"

# INTERNAL VARIABLES

LONG_URL=""
MESSAGE=""
OUTPUT=""

if [ -z "$URL" ]; then
  "$ECHO_BIN" "No URL given. See googl --help." >&2
  exit 1
fi

if [ $HELP -ne 0 ]; then
  "$ECHO_BIN" "googl"
  "$ECHO_BIN"
  "$ECHO_BIN" "usage: googl URL"
  exit 0
fi

"$ECHO_BIN" "$URL" | "$GREP_BIN" -qE "^http://goo.gl"

if [ $? -eq 0 ]; then
  ACTION=expand
fi

case $ACTION in
  expand)
    OUTPUT="$("$CURL_BIN" -s "$API/v1/url?shortUrl=$URL")"
    LONG_URL="$("$ECHO_BIN" "$OUTPUT" | "$GREP_BIN" -E \"longUrl\":)"
    if [ $? -eq 0 ]; then
      "$ECHO_BIN" "$LONG_URL" | "$SED_BIN" 's/.*"\([^"]*\)",$/\1/'
      exit 0
    fi
    MESSAGE="$("$ECHO_BIN" "$OUTPUT" | "$GREP_BIN" -E \"message\":)"
    if [ $? -eq 0 ]; then
      MESSAGE="$("$ECHO_BIN" "$MESSAGE" | "$SED_BIN" \$p)"
      MESSAGE="$("$ECHO_BIN" "$MESSAGE" | "$SED_BIN" 's/.*"\([^"]*\)"$/\1/')"
      "$ECHO_BIN" "Invalid response ($MESSAGE)." >&2
      exit 1
    fi
    exit 2
  ;;
  shorten)
    OUTPUT="$("$CURL_BIN" -s "$API/v1/url" -H 'Content-Type: application/json' -d "{\"longUrl\": \"$URL\"}")"
    SHORT_URL="$("$ECHO_BIN" "$OUTPUT" | "$GREP_BIN" -E \"id\":)"
    if [ $? -eq 0 ]; then
      SHORT_URL="$("$ECHO_BIN" "$SHORT_URL" | "$SED_BIN" 's/.*"\([^"]*\)",$/\1/')"
      "$ECHO_BIN" "$SHORT_URL"
      exit 0
    fi
    exit 2
  ;;
esac

exit 2

